name: Generata ASCII

on: push

jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v4

        - name: list repo
          run: ls -ltra

        - name: executing shell scripts
          run: |
            chmod +x ascii-script.sh
            ./ascii-script.sh

       
        