name: Myfirstpipeline

on: push

jobs:
    firstjob:
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v4  

        - name: hello world
          run: echo "estam vachindi rayi"  

        - name: list files  
          run: ls 
          
        - name: view files
          run: cat README.md

          
